#define private public
#include "MainComponent.h"
#undef private
#include <juce_gui_basics/juce_gui_basics.h>
#include <atomic>
#include <map>
#include <memory>
namespace{class OldSettingsCover final:public juce::Component{public:OldSettingsCover(){setInterceptsMouseClicks(true,true);setOpaque(true);}void paint(juce::Graphics&g)override{g.fillAll(juce::Colour(0xff15181d));}};class AudioSettingsRelocator final:private juce::Timer{public:explicit AudioSettingsRelocator(MainComponent&o):owner(o){button.setButtonText("AUDIO SETTINGS");button.setColour(juce::TextButton::buttonColourId,juce::Colour(0xff252a31));button.setColour(juce::TextButton::textColourOffId,juce::Colours::white);button.setMouseClickGrabsKeyboardFocus(false);button.onClick=[this]{owner.openAudioSettings();};owner.addAndMakeVisible(cover);owner.addAndMakeVisible(button);cover.setBounds(920,6,132,32);button.setBounds(313,8,128,26);startTimerHz(1);}~AudioSettingsRelocator()override{shutdown();}void shutdown(){if(stopped.exchange(true))return;stopTimer();cover.setVisible(false);button.setVisible(false);}private:void timerCallback()override{if(stopped.load())return;auto bb=juce::Rectangle<int>(313,8,128,26);if(button.getBounds()!=bb)button.setBounds(bb);auto cb=juce::Rectangle<int>(920,6,132,32);if(cover.getBounds()!=cb)cover.setBounds(cb);/* Critical: never call toFront here. SNAP and AI MUSIC must remain above this legacy mask. */}MainComponent&owner;OldSettingsCover cover;juce::TextButton button;std::atomic<bool>stopped{false};};std::map<MainComponent*,std::unique_ptr<AudioSettingsRelocator>>controllers;class Bootstrap final:private juce::Timer{public:Bootstrap(){startTimerHz(2);}~Bootstrap()override{shutdown();}void shutdown(){stopTimer();for(auto&i:controllers)if(i.second)i.second->shutdown();controllers.clear();}private:void timerCallback()override{auto&d=juce::Desktop::getInstance();for(int i=0;i<d.getNumComponents();++i)if(auto*w=dynamic_cast<juce::DocumentWindow*>(d.getComponent(i)))if(auto*m=dynamic_cast<MainComponent*>(w->getContentComponent()))if(!controllers.count(m))controllers.emplace(m,std::make_unique<AudioSettingsRelocator>(*m));}};Bootstrap bootstrap;}
void shutdownLibertyAudioSettingsRelocator(){bootstrap.shutdown();}
