#include "MainComponent.h"
#include <juce_gui_basics/juce_gui_basics.h>
#include <map>
#include <memory>
namespace{
using Dict=std::map<juce::String,juce::String>;
const Dict enToFr={
{"AUDIO SETTINGS","REGLAGES AUDIO"},{"BROWSER","NAVIGATEUR"},{"PROJECT","PROJET"},{"ARRANGE","ARRANGEMENT"},{"MIXCONSOLE","CONSOLE DE MIXAGE"},{"PERFORM","PERFORMANCE"},{"AI MUSIC","IA MUSICALE"},{"CLOSE","FERMER"},{"CLEAR MIDI","EFFACER MIDI"},{"GENERATE","GENERER"},{"CHORDS","ACCORDS"},{"DRUMMER","BATTERIE"},{"BASS","BASSE"},{"GUITAR RIFF","RIFF GUITARE"},{"SOLO","SOLO"},{"HUMANIZE","HUMANISER"},{"VARIATION","VARIATION"},{"HARMONIZE","HARMONISER"},{"CHORD TRACK","PISTE D'ACCORDS"},{"RENDER TO AUDIO","CONVERTIR EN AUDIO"},{"ARPEGGIATE","ARPEGER"},{"COUNTER MELODY","CONTRE-MELODIE"},{"GROOVE MUTATOR","VARIATION DE GROOVE"},{"SMART FILL","FILL INTELLIGENT"},{"SMART VOICING","VOICING INTELLIGENT"},{"ENERGY UP","AUGMENTER L'ENERGIE"},{"ENERGY DOWN","REDUIRE L'ENERGIE"},{"VARIATION PACK","PACK DE VARIATIONS"},{"BUILD SONG","CONSTRUIRE LE MORCEAU"},{"SHORT SONG","MORCEAU COURT"},{"MAKE INTRO","CREER INTRO"},{"MAKE CHORUS","CREER REFRAIN"},{"MAKE BRIDGE","CREER PONT"},{"ANALYSE IDEA","ANALYSER L'IDEE"},{"SMART DEVELOP","DEVELOPPEMENT INTELLIGENT"},{"TRANSITION","TRANSITION"},{"BREAKDOWN","BREAKDOWN"},{"CLIMAX","CLIMAX"},{"AI COMPOSER 2","COMPOSITEUR IA 2"},{"CLOSE COMPOSER","FERMER COMPOSITEUR"},{"GENERATE SECTION","GENERER LA SECTION"},{"FULL","COMPLET"},{"MELODY","MELODIE"},{"RIFF","RIFF"},{"MINOR","MINEUR"},{"MAJOR","MAJEUR"},{"PENTATONIC MINOR","PENTATONIQUE MINEURE"},{"COMPLEXITY","COMPLEXITE"},{"ENERGY","ENERGIE"},{"HUMAN FEEL","TOUCHE HUMAINE"},{"FILES","FICHIERS"},{"AUDIO","AUDIO"},{"MIDI","MIDI"},{"PRESETS","PRESETS"},{"PLUGINS","PLUGINS"},{"HOME","ACCUEIL"},{"FAVORITES","FAVORIS"},{"MIXER","MIXEUR"},{"RESET WARP","REINITIALISER WARP"},{"Beats","Rythme"},{"Tones","Tons"},{"Texture","Texture"},{"Re-Pitch","Re-Pitch"},{"Complex","Complexe"},{"RECORD TO ARRANGE","ENREGISTRER VERS ARRANGEMENT"},{"INSTRUMENT","INSTRUMENT"},{"STYLE","STYLE"},{"MOOD","AMBIANCE"},{"DARK","SOMBRE"},{"BRIGHT","LUMINEUX"},{"TENSE","TENDU"},{"EPIC","EPIQUE"},{"MELANCHOLIC","MELANCOLIQUE"},{"AGGRESSIVE","AGRESSIF"},{"DREAMY","ONIRIQUE"},{"ROCK","ROCK"},{"METAL","METAL"},{"FUNK","FUNK"},{"BLUES","BLUES"},{"AMBIENT","AMBIENT"},{"CINEMATIC","CINEMATIQUE"},{"ELECTRONIC","ELECTRONIQUE"}};
juce::String translateExact(const juce::String&s,bool french){if(french){auto i=enToFr.find(s);return i==enToFr.end()?s:i->second;}for(auto&i:enToFr)if(i.second==s)return i.first;return s;}
void translateTree(juce::Component&c,bool french,juce::Component*skip){if(&c!=skip){if(auto*b=dynamic_cast<juce::Button*>(&c)){auto old=b->getButtonText();auto t=translateExact(old,french);if(t!=old)b->setButtonText(t);}if(auto*l=dynamic_cast<juce::Label*>(&c)){auto old=l->getText();auto t=translateExact(old,french);if(t!=old)l->setText(t,juce::dontSendNotification);}}
for(int i=0;i<c.getNumChildComponents();++i)if(auto*ch=c.getChildComponent(i))translateTree(*ch,french,skip);c.repaint();}
class Controller:private juce::Timer{public:explicit Controller(MainComponent&o):owner(o){language.addItem("English",1);language.addItem("Francais",2);auto f=file();auto v=f.existsAsFile()?f.loadFileAsString().trim():"English";language.setSelectedId(v=="Francais"?2:1,juce::dontSendNotification);language.onChange=[this]{apply(true);};owner.addAndMakeVisible(language);startTimerHz(2);apply(false);}~Controller(){shutdown();}void shutdown(){stopTimer();language.setVisible(false);}private:juce::File file()const{return juce::File::getSpecialLocation(juce::File::userApplicationDataDirectory).getChildFile("BSM").getChildFile("Liberty").getChildFile("Language.txt");}void apply(bool save){bool fr=language.getSelectedId()==2;translateTree(owner,fr,&language);language.setTooltip(fr?"Langue de l'interface Liberty":"Liberty interface language");if(save){auto f=file();f.getParentDirectory().createDirectory();f.replaceWithText(fr?"Francais":"English");}}void timerCallback()override{int x=448;language.setBounds(x,8,104,26);language.toFront(false);apply(false);}MainComponent&owner;juce::ComboBox language;};
std::map<MainComponent*,std::unique_ptr<Controller>>cs;class Boot:private juce::Timer{public:Boot(){startTimerHz(3);}~Boot(){shutdown();}void shutdown(){stopTimer();cs.clear();}private:void timerCallback()override{auto&d=juce::Desktop::getInstance();for(int i=0;i<d.getNumComponents();++i)if(auto*w=dynamic_cast<juce::DocumentWindow*>(d.getComponent(i)))if(auto*m=dynamic_cast<MainComponent*>(w->getContentComponent()))if(!cs.count(m))cs.emplace(m,std::make_unique<Controller>(*m));}}boot;}
void shutdownLibertyLanguageController(){boot.shutdown();}
