#define private public
#include "MainComponent.h"
#undef private
#include "PluginHost.h"
#include "OneKnobEffects.h"
#include <juce_gui_basics/juce_gui_basics.h>
#include <atomic>
#include <cmath>
#include <map>
#include <memory>
#include <vector>

int getLibertyTrackColourId(int track);
juce::String getLibertyTrackName(int track);

namespace {
constexpr int transportHeight=76, stripW=142, topY=66;
float gainToDb(float g){return g<=.00001f?-60.f:juce::jlimit(-60.f,6.f,juce::Decibels::gainToDecibels(g));}
float dbToGain(float d){return d<=-59.9f?0.f:juce::Decibels::decibelsToGain(d);}
juce::Colour trackColour(int id){static constexpr juce::uint32 palette[]{0xff31506a,0xff3b82f6,0xff22c55e,0xffeab308,0xfff97316,0xffef4444,0xffa855f7,0xffec4899,0xff14b8a6};return juce::Colour(palette[(size_t)juce::jlimit(0,8,id)]);}
struct Strip{enum Kind{audio,midi,instrument,master}kind=audio;int lane=0;std::unique_ptr<juce::Slider>fader,pan;std::unique_ptr<juce::TextButton>mute,solo,plugin,unload;juce::Rectangle<int>bounds;};
class MixConsoleView final:public juce::Component,private juce::Timer{
public:
 explicit MixConsoleView(MainComponent&o):owner(o){scrollListener.o=this;setOpaque(true);setInterceptsMouseClicks(true,true);scroll.setRangeLimits(0,1);scroll.addListener(&scrollListener);addAndMakeVisible(scroll);owner.addAndMakeVisible(this);startTimerHz(20);setVisible(false);}
 ~MixConsoleView()override{stopTimer();scroll.removeListener(&scrollListener);clear();}
 void setConsoleVisible(bool b){visible=b;setVisible(b);if(b){setBounds(0,transportHeight,owner.getWidth(),juce::jmax(1,owner.getHeight()-transportHeight));rebuild();toFront(false);}else{selected=nullptr;}}
 bool isConsoleVisible()const{return visible;}
 int getDropTrackForOwnerPoint(juce::Point<int> p,bool instrumentPlugin)const{if(!visible)return-1;auto q=p-juce::Point<int>(0,transportHeight);for(auto&s:strips)if(s->bounds.contains(q)){if(instrumentPlugin&&s->kind==Strip::instrument)return owner.getAudioTrackCount()+owner.getMidiTrackCount()+s->lane;if(!instrumentPlugin&&s->kind==Strip::audio)return s->lane;}return-1;}
 void paint(juce::Graphics&g)override{g.fillAll(juce::Colour(0xff0d1014));g.setColour(juce::Colour(0xff171c22));g.fillRect(0,0,getWidth(),54);g.setColour(juce::Colours::white);g.setFont(juce::Font(20.f,juce::Font::bold));g.drawText("MIXCONSOLE",24,10,190,28,juce::Justification::centredLeft);for(auto&s:strips)draw(g,*s);}
 void resized()override{layout();}
 void mouseDown(const juce::MouseEvent&e)override{for(auto&s:strips)if(s->bounds.contains(e.getPosition())){if(s->kind==Strip::master){selected=nullptr;repaint();break;}selected=s.get();owner.selectedTrack=s->kind==Strip::audio?s->lane:(s->kind==Strip::midi?owner.getAudioTrackCount()+s->lane:owner.getAudioTrackCount()+owner.getMidiTrackCount()+s->lane);repaint();owner.repaint();break;}}
private:
 struct ScrollListener:juce::ScrollBar::Listener{MixConsoleView*o=nullptr;void scrollBarMoved(juce::ScrollBar*,double v)override{if(o){o->offset=(int)std::round(v);o->layout();o->repaint();}}}scrollListener;
 void clear(){selected=nullptr;for(auto&s:strips){if(s->fader)s->fader->setLookAndFeel(nullptr);if(s->pan)s->pan->setLookAndFeel(nullptr);}strips.clear();}
 std::unique_ptr<Strip> makeStrip(Strip::Kind k,int lane){auto s=std::make_unique<Strip>();s->kind=k;s->lane=lane;s->fader=std::make_unique<juce::Slider>();s->fader->setSliderStyle(juce::Slider::LinearVertical);s->fader->setRange(-60,6,.1);s->fader->setTextBoxStyle(juce::Slider::TextBoxBelow,false,62,20);s->fader->setTextValueSuffix(" dB");addAndMakeVisible(*s->fader);if(k==Strip::audio||k==Strip::instrument){s->pan=std::make_unique<juce::Slider>();s->pan->setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s->pan->setRange(-1,1,.01);s->pan->setTextBoxStyle(juce::Slider::NoTextBox,false,0,0);addAndMakeVisible(*s->pan);s->mute=std::make_unique<juce::TextButton>("M");s->solo=std::make_unique<juce::TextButton>("S");s->mute->setClickingTogglesState(false);s->solo->setClickingTogglesState(false);s->mute->setColour(juce::TextButton::buttonColourId,juce::Colour(0xff31363e));s->solo->setColour(juce::TextButton::buttonColourId,juce::Colour(0xff31363e));s->mute->setColour(juce::TextButton::buttonOnColourId,juce::Colour(0xff9b4545));s->solo->setColour(juce::TextButton::buttonOnColourId,juce::Colour(0xff8b7a32));s->mute->setColour(juce::TextButton::textColourOffId,juce::Colours::white);s->solo->setColour(juce::TextButton::textColourOffId,juce::Colours::white);s->mute->setColour(juce::TextButton::textColourOnId,juce::Colours::white);s->solo->setColour(juce::TextButton::textColourOnId,juce::Colours::white);addAndMakeVisible(*s->mute);addAndMakeVisible(*s->solo);}s->plugin=std::make_unique<juce::TextButton>();s->unload=std::make_unique<juce::TextButton>("x");addAndMakeVisible(*s->plugin);addAndMakeVisible(*s->unload);wire(*s);return s;}
 void wire(Strip&s){auto*sp=&s;if(sp->kind==Strip::midi){s.fader->setEnabled(false);s.plugin->setEnabled(false);s.unload->setEnabled(false);return;}s.fader->onValueChange=[this,sp]{if(syncing)return;float g=dbToGain((float)sp->fader->getValue());if(sp->kind==Strip::audio)owner.audioEngine.setTrackGain(sp->lane,g);else if(sp->kind==Strip::instrument)owner.audioEngine.setInstrumentTrackGain(sp->lane,g);else owner.audioEngine.setMasterGain(g);};if(s.pan)s.pan->onValueChange=[this,sp]{if(syncing)return;float p=(float)sp->pan->getValue();if(sp->kind==Strip::audio)owner.audioEngine.setTrackPan(sp->lane,p);else owner.audioEngine.setInstrumentTrackPan(sp->lane,p);};if(s.mute)s.mute->onClick=[this,sp]{if(sp->kind==Strip::audio)owner.audioEngine.setTrackMuted(sp->lane,!owner.audioEngine.isTrackMuted(sp->lane));else owner.audioEngine.setInstrumentTrackMuted(sp->lane,!owner.audioEngine.isInstrumentTrackMuted(sp->lane));};if(s.solo)s.solo->onClick=[this,sp]{if(sp->kind==Strip::audio)owner.audioEngine.setTrackSolo(sp->lane,!owner.audioEngine.isTrackSolo(sp->lane));else owner.audioEngine.setInstrumentTrackSolo(sp->lane,!owner.audioEngine.isInstrumentTrackSolo(sp->lane));};s.plugin->onClick=[sp]{auto&h=LibertyPluginHost::instance();auto&k=LibertyOneKnobManager::instance();int slot=sp->kind==Strip::instrument?100000+sp->lane:sp->lane;if(sp->kind!=Strip::master&&k.hasEffect(slot))k.showEditor(slot);else if(sp->kind==Strip::audio&&h.hasEffectForTrack(sp->lane))h.showEditorForTrack(sp->lane);else if(sp->kind==Strip::instrument&&h.hasInstrumentForTrack(sp->lane))h.showInstrumentEditorForTrack(sp->lane);};s.unload->onClick=[this,sp]{auto&h=LibertyPluginHost::instance();auto&k=LibertyOneKnobManager::instance();int slot=sp->kind==Strip::instrument?100000+sp->lane:sp->lane;if(k.hasEffect(slot))k.clearEffect(slot);else if(sp->kind==Strip::audio)h.unloadEffectForTrack(sp->lane);else if(sp->kind==Strip::instrument)h.unloadInstrumentForTrack(sp->lane);sync();};}
 void rebuild(){const int audio=owner.getAudioTrackCount(),midi=owner.getMidiTrackCount(),instrument=owner.getInstrumentTrackCount();const int need=audio+midi+instrument+1;bool matches=need==(int)strips.size();if(matches){int p=0;for(int i=0;i<audio&&matches;++i,++p)matches=strips[(size_t)p]->kind==Strip::audio&&strips[(size_t)p]->lane==i;for(int i=0;i<midi&&matches;++i,++p)matches=strips[(size_t)p]->kind==Strip::midi&&strips[(size_t)p]->lane==i;for(int i=0;i<instrument&&matches;++i,++p)matches=strips[(size_t)p]->kind==Strip::instrument&&strips[(size_t)p]->lane==i;if(matches)matches=strips[(size_t)p]->kind==Strip::master;}const int arrangeTracks=audio+midi+instrument;if(matches){if(arrangeTracks<=0)owner.selectedTrack=-1;return;}if(arrangeTracks<=0)owner.selectedTrack=-1;const auto selectedKind=selected?selected->kind:Strip::master;const int selectedLane=selected?selected->lane:-1;clear();for(int i=0;i<audio;++i)strips.push_back(makeStrip(Strip::audio,i));for(int i=0;i<midi;++i)strips.push_back(makeStrip(Strip::midi,i));for(int i=0;i<instrument;++i)strips.push_back(makeStrip(Strip::instrument,i));strips.push_back(makeStrip(Strip::master,0));if(selectedLane>=0){for(auto&candidate:strips)if(candidate->kind==selectedKind&&candidate->lane==selectedLane){selected=candidate.get();break;}if(selected==nullptr)owner.selectedTrack=arrangeTracks>0?juce::jlimit(0,arrangeTracks-1,owner.selectedTrack):-1;}layout();sync();}
 void layout(){int h=juce::jmax(480,getHeight()-topY-38),x=12-offset;for(auto&s:strips){s->bounds={x,topY,stripW-4,h};bool vis=s->bounds.getRight()>0&&s->bounds.getX()<getWidth();for(auto*c:{(juce::Component*)s->fader.get(),(juce::Component*)s->pan.get(),(juce::Component*)s->mute.get(),(juce::Component*)s->solo.get(),(juce::Component*)s->plugin.get(),(juce::Component*)s->unload.get()})if(c)c->setVisible(vis);if(vis){int cx=s->bounds.getCentreX();s->plugin->setBounds(s->bounds.getX()+8,s->bounds.getY()+88,s->bounds.getWidth()-44,28);s->unload->setBounds(s->bounds.getRight()-32,s->bounds.getY()+88,24,28);if(s->kind==Strip::audio||s->kind==Strip::instrument){s->pan->setBounds(cx-22,s->bounds.getY()+142,44,44);s->mute->setBounds(cx-46,s->bounds.getY()+200,40,26);s->solo->setBounds(cx+6,s->bounds.getY()+200,40,26);}s->fader->setBounds(cx-34,s->bounds.getY()+270,68,juce::jmax(150,s->bounds.getHeight()-350));}x+=stripW;}int total=(int)strips.size()*stripW,max=juce::jmax(0,total-getWidth()+24);const int clamped=juce::jlimit(0,max,offset);if(clamped!=offset){offset=clamped;x=12-offset;for(auto&s:strips){s->bounds.setX(x);x+=stripW;}}scroll.setBounds(12,getHeight()-24,getWidth()-24,16);scroll.setRangeLimits(0,juce::jmax(1,max+getWidth()));scroll.setCurrentRange(offset,getWidth(),juce::dontSendNotification);scroll.setVisible(max>0);}
 juce::String name(const Strip&s)const{if(s.kind==Strip::master)return "MASTER";const int logical=s.kind==Strip::audio?s.lane:(s.kind==Strip::midi?owner.getAudioTrackCount()+s.lane:owner.getAudioTrackCount()+owner.getMidiTrackCount()+s.lane);const auto n=getLibertyTrackName(logical);if(n.isNotEmpty())return n;if(s.kind==Strip::audio)return "Audio "+juce::String(s.lane+1);if(s.kind==Strip::midi)return "MIDI "+juce::String(s.lane+1);return "Instrument "+juce::String(s.lane+1);}
 void draw(juce::Graphics&g,Strip&s){if(s.bounds.isEmpty()||s.bounds.getRight()<0||s.bounds.getX()>getWidth())return;g.setColour(selected==&s?juce::Colour(0xff202b34):juce::Colour(0xff15191f));g.fillRoundedRectangle(s.bounds.toFloat(),6);if(s.kind!=Strip::master){const int logical=s.kind==Strip::audio?s.lane:(s.kind==Strip::midi?owner.getAudioTrackCount()+s.lane:owner.getAudioTrackCount()+owner.getMidiTrackCount()+s.lane);const int colourId=getLibertyTrackColourId(logical);if(colourId!=0){const auto c=trackColour(colourId);g.setColour(c.withAlpha(0.18f));g.fillRoundedRectangle(s.bounds.toFloat(),6);g.setColour(c);g.fillRect(s.bounds.getX(),s.bounds.getY(),s.bounds.getWidth(),4);}}g.setColour(juce::Colour(0xff343b45));g.drawRoundedRectangle(s.bounds.toFloat(),6,1);g.setColour(juce::Colours::white);g.setFont(juce::Font(12.f,juce::Font::bold));g.drawText(name(s),s.bounds.getX()+6,s.bounds.getY()+14,s.bounds.getWidth()-12,20,juce::Justification::centred);g.setColour(juce::Colour(0xff8f98a3));g.setFont(juce::Font(8.f,juce::Font::bold));g.drawText(s.kind==Strip::audio?"AUDIO CHANNEL":s.kind==Strip::midi?"MIDI TRACK":s.kind==Strip::instrument?"VIRTUAL INSTRUMENT":"STEREO MASTER",s.bounds.getX()+4,s.bounds.getY()+36,s.bounds.getWidth()-8,15,juce::Justification::centred);}
 void sync(){syncing=true;auto&h=LibertyPluginHost::instance();auto&k=LibertyOneKnobManager::instance();for(auto&s:strips){if(s->kind==Strip::audio){s->fader->setValue(gainToDb(owner.audioEngine.getTrackGain(s->lane)),juce::dontSendNotification);s->pan->setValue(owner.audioEngine.getTrackPan(s->lane),juce::dontSendNotification);bool ko=k.hasEffect(s->lane),ho=h.hasEffectForTrack(s->lane);s->plugin->setButtonText(ko?k.getName(s->lane):(ho?h.getEffectName(s->lane):"INSERT - EMPTY"));s->unload->setEnabled(ko||ho);s->mute->setToggleState(owner.audioEngine.isTrackMuted(s->lane),juce::dontSendNotification);s->solo->setToggleState(owner.audioEngine.isTrackSolo(s->lane),juce::dontSendNotification);}else if(s->kind==Strip::midi){s->fader->setValue(-60.0,juce::dontSendNotification);s->fader->setTextValueSuffix("");s->plugin->setButtonText("MIDI");s->plugin->setEnabled(false);s->unload->setEnabled(false);}else if(s->kind==Strip::instrument){s->fader->setValue(gainToDb(owner.audioEngine.getInstrumentTrackGain(s->lane)),juce::dontSendNotification);s->pan->setValue(owner.audioEngine.getInstrumentTrackPan(s->lane),juce::dontSendNotification);int slot=100000+s->lane;bool ko=k.hasEffect(slot),ho=h.hasInstrumentForTrack(s->lane);juce::String n=ho?h.getInstrumentNameForTrack(s->lane):"INSTRUMENT - EMPTY";if(ko)n<<" + "<<k.getName(slot);s->plugin->setButtonText(n);s->unload->setEnabled(ko||ho);s->mute->setToggleState(owner.audioEngine.isInstrumentTrackMuted(s->lane),juce::dontSendNotification);s->solo->setToggleState(owner.audioEngine.isInstrumentTrackSolo(s->lane),juce::dontSendNotification);}else{s->fader->setValue(gainToDb(owner.audioEngine.getMasterGain()),juce::dontSendNotification);s->plugin->setButtonText("MASTER OUTPUT");s->plugin->setEnabled(false);s->unload->setEnabled(false);}}syncing=false;}
 void timerCallback()override{if(!visible)return;auto wanted=juce::Rectangle<int>(0,transportHeight,owner.getWidth(),juce::jmax(1,owner.getHeight()-transportHeight));if(getBounds()!=wanted)setBounds(wanted);rebuild();sync();repaint();}
 MainComponent&owner;std::vector<std::unique_ptr<Strip>>strips;juce::ScrollBar scroll{false};int offset=0;bool syncing=false,visible=false;Strip*selected=nullptr;
};
class MixConsoleController final:private juce::Timer{public:explicit MixConsoleController(MainComponent&o):owner(o),view(o){arrange.setButtonText("ARRANGE");mix.setButtonText("MIXCONSOLE");for(auto*b:{&arrange,&mix}){b->setMouseClickGrabsKeyboardFocus(false);owner.addAndMakeVisible(*b);}arrange.onClick=[this]{show(false);};mix.onClick=[this]{show(true);};startTimerHz(10);}~MixConsoleController()override{shutdown();}void shutdown(){if(stopped.exchange(true))return;stopTimer();shown=false;view.setConsoleVisible(false);arrange.setVisible(false);mix.setVisible(false);}void show(bool b){if(stopped.load())return;shown=b;view.setConsoleVisible(b);arrange.toFront(false);mix.toFront(false);owner.repaint();}bool isVisible()const{return shown;}int getDropTrack(juce::Point<int>p,bool i)const{return view.getDropTrackForOwnerPoint(p,i);}private:void timerCallback()override{if(stopped)return;arrange.setBounds(1055,8,88,26);mix.setBounds(1147,8,112,26);arrange.toFront(false);mix.toFront(false);}MainComponent&owner;MixConsoleView view;juce::TextButton arrange,mix;std::atomic<bool>stopped{false};bool shown=false;};
std::map<MainComponent*,std::unique_ptr<MixConsoleController>>controllers;
class Bootstrap final:private juce::Timer{public:Bootstrap(){startTimerHz(10);}~Bootstrap()override{shutdown();}void shutdown(){stopTimer();for(auto&p:controllers)if(p.second)p.second->shutdown();controllers.clear();}private:void timerCallback()override{auto&d=juce::Desktop::getInstance();for(int i=0;i<d.getNumComponents();++i)if(auto*w=dynamic_cast<juce::DocumentWindow*>(d.getComponent(i)))if(auto*m=dynamic_cast<MainComponent*>(w->getContentComponent()))if(!controllers.count(m))controllers.emplace(m,std::make_unique<MixConsoleController>(*m));}};Bootstrap bootstrap;
}
bool isLibertyMixConsoleVisible(MainComponent*o){auto i=controllers.find(o);return o&&i!=controllers.end()&&i->second&&i->second->isVisible();}
int getLibertyMixConsolePluginDropTrack(MainComponent*o,juce::Point<int>p,bool i){auto it=controllers.find(o);return o&&it!=controllers.end()&&it->second?it->second->getDropTrack(p,i):-1;}
void shutdownLibertyMixConsoleController(){bootstrap.shutdown();}
