#include "MainComponent.h"
#include <juce_gui_basics/juce_gui_basics.h>
#include <map>
#include <memory>
#include <array>

void toggleLibertyMidiInstrumentMute(MainComponent& owner);
namespace{
enum class Tool{select,draw,split,erase,resize,stretch,velocity,marquee,mute};
Tool activeTool=Tool::select;
const char* toolShortcuts[]={"1","2","3","4","5","6","7","8","9"};
bool paletteVisible=false;
class Palette final:public juce::Component{public:explicit Palette(MainComponent&o):owner(&o){setOpaque(true);audio.setButtonText("AUDIO");midi.setButtonText("MIDI");audio.setClickingTogglesState(true);midi.setClickingTogglesState(true);audio.setRadioGroupId(7101);midi.setRadioGroupId(7101);audio.setToggleState(true,juce::dontSendNotification);audio.onClick=[this]{modeMidi=false;refresh();};midi.onClick=[this]{modeMidi=true;refresh();};addAndMakeVisible(audio);addAndMakeVisible(midi);const char*names[]={"SELECT","DRAW","SPLIT","ERASE","RESIZE","STRETCH","VELOCITY","MARQUEE","MUTE"};for(int i=0;i<9;++i){buttons[i].setButtonText(names[i]);buttons[i].setClickingTogglesState(true);buttons[i].setRadioGroupId(7201);buttons[i].onClick=[this,i]{activeTool=(Tool)i;if(i==8&&modeMidi&&owner)toggleLibertyMidiInstrumentMute(*owner);refresh();};buttons[i].setTooltip(juce::String(names[i])+"  ["+toolShortcuts[i]+"]");addAndMakeVisible(buttons[i]);}refresh();}void paint(juce::Graphics&g)override{g.fillAll(juce::Colour(0xff11161c));g.setColour(juce::Colour(0xff63c7e8));g.drawRoundedRectangle(getLocalBounds().toFloat().reduced(1),6,1.5f);g.setColour(juce::Colour(0xffc9d2db));g.setFont(juce::Font(11,juce::Font::bold));g.drawText("LIBERTY TOOLS",10,5,getWidth()-20,20,juce::Justification::centredLeft);
for(int i=0;i<9;++i){auto b=buttons[i].getBounds();g.setColour(juce::Colour(0xff8e99a5));g.setFont(juce::Font(9.0f));g.drawText(toolShortcuts[i],b.getRight()-15,b.getY()+1,12,10,juce::Justification::centred);}}void resized()override{audio.setBounds(10,28,82,26);midi.setBounds(98,28,82,26);int x=10,y=62;for(int i=0;i<9;++i){buttons[i].setBounds(x,y,82,28);x+=88;if(x+82>getWidth()){x=10;y+=34;}}}bool keyPressed(const juce::KeyPress& k) override {const auto ch=k.getTextCharacter();if(ch>='1'&&ch<='9'){const int i=(int)(ch-'1');if(buttons[i].isEnabled()){activeTool=(Tool)i;buttons[i].triggerClick();return true;}}return false;}private:void refresh(){for(int i=0;i<9;++i){bool allowed=modeMidi?(i==0||i==1||i==3||i==4||i==6||i==7||i==8):(i==0||i==2||i==3||i==4||i==5||i==8);buttons[i].setEnabled(allowed);buttons[i].setToggleState(allowed&&i==(int)activeTool,juce::dontSendNotification);
buttons[i].setColour(juce::TextButton::buttonColourId,(allowed&&i==(int)activeTool)?juce::Colour(0xff167c9f):juce::Colour(0xff252a31));
buttons[i].setColour(juce::TextButton::textColourOffId,(allowed&&i==(int)activeTool)?juce::Colours::white:juce::Colour(0xffd7dde3));}if(!buttons[(int)activeTool].isEnabled()){activeTool=Tool::select;buttons[0].setToggleState(true,juce::dontSendNotification);}}MainComponent* owner=nullptr;bool modeMidi=false;juce::TextButton audio,midi;std::array<juce::TextButton,9>buttons;};
class Controller:private juce::Timer{public:explicit Controller(MainComponent&o):owner(o){launcher.setButtonText("TOOLS");launcher.setColour(juce::TextButton::buttonColourId,juce::Colour(0xff252a31));launcher.onClick=[this]{paletteVisible=!paletteVisible;if(box){box->setVisible(paletteVisible);if(paletteVisible){box->toFront(false);box->setWantsKeyboardFocus(true);box->grabKeyboardFocus();}}};owner.addAndMakeVisible(launcher);box=std::make_unique<Palette>(owner);owner.addChildComponent(*box);box->setVisible(false);startTimerHz(2);}~Controller(){shutdown();}void shutdown(){stopTimer();box.reset();launcher.setVisible(false);}private:void timerCallback()override{launcher.setBounds(558,8,74,26);launcher.toFront(false);if(box){int w=juce::jmin(380,juce::jmax(280,owner.getWidth()-40));box->setBounds(juce::jmax(10,(owner.getWidth()-w)/2),82,w,170);if(paletteVisible)box->toFront(false);}}MainComponent&owner;juce::TextButton launcher;std::unique_ptr<Palette>box;};std::map<MainComponent*,std::unique_ptr<Controller>>cs;class Boot:private juce::Timer{public:Boot(){startTimerHz(3);}~Boot(){shutdown();}void shutdown(){stopTimer();cs.clear();}private:void timerCallback()override{auto&d=juce::Desktop::getInstance();for(int i=0;i<d.getNumComponents();++i)if(auto*w=dynamic_cast<juce::DocumentWindow*>(d.getComponent(i)))if(auto*m=dynamic_cast<MainComponent*>(w->getContentComponent()))if(!cs.count(m))cs.emplace(m,std::make_unique<Controller>(*m));}}boot;}
int getLibertyActiveTool(){return(int)activeTool;}void shutdownLibertyToolPaletteController(){boot.shutdown();}
